version: '3.5'

services:
  ongradient-mongo-db:
    container_name: ongradient-mongo-db
    image: mongo:4
    restart: always
    expose:
      - ${MONGO_PORT}
    ports:
      - ${MONGO_EXTERNAL_PORT}:${MONGO_PORT}
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_ADMIN_PWD
      - MONGO_INITDB_DATABASE=$DB_NAME
    volumes:
      - ongradient-data:/var/lib/mongo/data
    networks:
      - ongradient
    restart: always

  postgres-db:
    container_name: postgre_db
    image: 'postgres:12'
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    expose:
      - ${POSTGRES_EXTERNAL_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-ongradient}
    volumes:
      - ongradient-data:/var/lib/postgresql/data
    networks:
      - ongradient

  pg-admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_EXTERNAL_PORT}:${PGADMIN_PORT}
    restart: unless-stopped
    expose:
      - ${PGADMIN_EXTERNAL_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres-db
    networks:
      - ongradient

  api-server:
    container_name: ongradient_api
    image: node:12
    working_dir: /usr/src/api-server
    env_file: .env
    ports:
      - $API_EXTERNAL_PORT:$API_PORT
    expose:
      - $API_EXTERNAL_PORT
    volumes:
      - ./:/usr/src/api-server
    depends_on:
      - postgres-db
      - ongradient-mongo-db
    networks:
      - ongradient
    command: npm run start:dev

volumes:
  ongradient-data:
  pgadmin:

networks:
  ongradient:
    name: ongradient-dev-network
